name: Deploy to Pages

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches: main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  render:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set Up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies
      run: |
        R -e 'options(repos = c(CRAN = "https://cloud.r-project.org"))'
        R -e 'install.packages(c("glue", "jsonlite"), dependencies = TRUE)'

    - name: Render RMarkdown
      run: |
        Rscript -e 'source("build.R")'

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
